[package]
name = "rust_test_project"
version = "0.1.0"
authors = ["Julian Schmid <info@julianschmid.name>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
