name: codecoverage 

on: [ push, pull_request ]

jobs:
  codecoverage_test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions-rs/toolchain@v1.0.6
      with:
        toolchain: nightly
        override: true
    - name: cargo test (instrumented)
      uses: JulianSchmid/actions-rs-coverage@v0.1.0