name: test-run

on: [ push, pull_request ]

jobs:
  test_coverage:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions-rs/toolchain@v1.0.6
      with:
        toolchain: nightly
        components: llvm-tools-preview
    - uses: actions-rs/cargo@v1
      with:
        command: install
        toolchain: nightly
        args: 
        - cargo-binutils
        - rustfilt
    - name: cargo test coverage (source based)
      uses: ./